# fw_version.py: write src/fw_version.h with the firmware's version (PIZERO-156).
#
# FW_VERSION is `git describe --always --dirty` (a tag if there is one, else
# the commit, with -dirty when the working tree has uncommitted changes),
# FW_DATE the commit's date and FW_ENV the build env. Shown on the F1 INFO
# page. The file is generated, gitignored, and rewritten only when a value
# changes, so it does not force a rebuild on every build. Wired in as a pre:
# extra_script in platformio.ini.

Import("env")  # noqa: F821  (provided by PlatformIO)

import os
import subprocess


def git(*args):
    try:
        return subprocess.check_output(("git",) + args, cwd=env.subst("$PROJECT_DIR"),  # noqa: F821
                                       stderr=subprocess.DEVNULL, text=True).strip()
    except Exception:
        return "unknown"


version = git("describe", "--always", "--dirty", "--abbrev=7")
date = git("log", "-1", "--format=%cd", "--date=format:%Y-%m-%d")
# Reproducible builds: FW_VERSION_OVERRIDE / FW_DATE_OVERRIDE pin both, so two
# builds of different trees can be compared byte for byte (PIZERO-174).
version = os.environ.get("FW_VERSION_OVERRIDE", version)
date = os.environ.get("FW_DATE_OVERRIDE", date)
pioenv = env.subst("$PIOENV")  # noqa: F821

text = (
    "// Generated by scripts/fw_version.py; do not edit, do not commit.\n"
    "#pragma once\n"
    '#define FW_VERSION "%s"\n'
    '#define FW_DATE "%s"\n'
    '#define FW_ENV "%s"\n' % (version, date, pioenv)
)
path = os.path.join(env.subst("$PROJECT_DIR"), "src", "fw_version.h")  # noqa: F821
old = open(path).read() if os.path.exists(path) else ""
if old != text:
    with open(path, "w") as f:
        f.write(text)
    print("fw_version: %s %s %s" % (version, date, pioenv))
