#!/usr/bin/env python3
"""Generate the 6847T2 font from the 6847T1 font (PIZERO-166).

The 6847T2 is this project's own font: the MC6847T1's, with the characters
it gets wrong for a modern keyboard put right. Run from the repo root:

    python3 scripts/make_font_6847t2.py

It reads lib/xroar_core/src/mc6847/font-6847t1.c and writes
lib/coco_machine/src/font_6847t2.c. Do not edit the output by hand; change
this script and run it again.

Glyph slots are the T1's: $00-$1F lower case (ASCII $60-$7F), $20-$3F
inverse punctuation, $40-$5F @ A-Z [ \\ ] and two arrows, $60-$7F space to ?.
Rows are 12 bytes, pixels MSB first; letters use columns 2-6, rows 1-7.
"""

import re
import sys

SRC = "lib/xroar_core/src/mc6847/font-6847t1.c"
DST = "lib/coco_machine/src/font_6847t2.c"


def rows(*r):
    """A glyph from up to 12 row bytes, padded with blank rows."""
    return list(r) + [0] * (12 - len(r))


# The T1 keeps its caret and underscore in the lower-case block, at the
# backtick and DEL slots, and draws ^ and _ as arrows. The T2 moves them.
CHANGES = {}


def main():
    text = open(SRC).read()
    font = [int(x, 16) for x in re.findall(r"0x([0-9a-fA-F]{2})", text.split("{", 1)[1])]
    if len(font) != 1536:
        sys.exit("expected 1536 bytes in %s, found %d" % (SRC, len(font)))

    def glyph(i):
        return font[i * 12:(i + 1) * 12]

    caret, underscore = glyph(0x00), glyph(0x1F)
    CHANGES[0x5E] = ("^  a caret, not the 6847's up arrow", caret)
    CHANGES[0x5F] = ("_  an underscore, not the 6847's left arrow", underscore)
    CHANGES[0x00] = ("`  a backtick (the T1 has none: it drew a caret here)",
                     rows(0x00, 0x20, 0x10, 0x18, 0x18))
    CHANGES[0x1F] = ("DEL  a house, as the IBM PC shows it (the T1 put its underscore here)",
                     rows(0x00, 0x08, 0x14, 0x22, 0x22, 0x22, 0x3E))

    out = list(font)
    for slot, (_, g) in CHANGES.items():
        out[slot * 12:(slot + 1) * 12] = g

    lines = [
        "/* Generated by scripts/make_font_6847t2.py from font-6847t1.c; do not edit. */",
        "/* PIZERO-166: the 6847T2, this project's font. Changes from the 6847T1: */",
    ]
    for slot in sorted(CHANGES):
        lines.append("/*   $%02X %s */" % (slot, CHANGES[slot][0]))
    lines += ["", "#include <stdint.h>", "", "const uint8_t font_6847t2[1536] = {"]
    for i in range(0, 1536, 12):
        lines.append("\t" + ", ".join("0x%02x" % b for b in out[i:i + 12]) + ",")
    lines += ["};", ""]
    open(DST, "w").write("\n".join(lines))
    print("wrote %s (%d glyphs changed)" % (DST, len(CHANGES)))


if __name__ == "__main__":
    main()
